export const SET_INFO_COMPANY = "SET_INFO_COMPANY";
export const UPDATE_INFO_COMPANY = "UPDATE_INFO_COMPANY";
export const LOADING_COMPANY = "LOADING_COMPANY";
export const SET_GRAPH_DATA = "SET_GRAPH_DATA";
export const SEARCH_SYMBOLS = "SEARCH_SYMBOLS";
export const SET_COMPANIES_LIST = "SET_COMPANIES_LIST";